### ISSUE TITLE
How does get_models.py --model [modelname] work

### ISSUE THREAD

**Issue by Waffled-II** [serkansulun/deep-music-enhancer#1]
I can't find any models through there. I tried doing DSD100 through it but no luck. Is there an example I can use?

**Comment by serkansulun** [comment]
For example, for unet, it should work as the following:
```
cd output/models
python get_models.py --model unet
```
It might take some time, each model is around 600 MB.

And to be clear, DSD100 is the dataset, not model. To download it:
```
cd datasets
python get_datasets.py
```
