### ISSUE TITLE
url in get_model.py is not work

### ISSUE THREAD

**Issue by pangr** [serkansulun/deep-music-enhancer#3]
<img width="1434" alt="图片" src="https://user-images.githubusercontent.com/5838111/114853719-a898fe00-9e16-11eb-85b9-c9ec89c0ab6a.png">

**Comment by serkansulun** [comment]
I'm not sure, but it looks like a network problem. Maybe you can try downloading the models manually, and then put into the `models` folder.

In `get_model.py`, there are Google drive file IDs for each model. You can convert them to url by writing them after `https://drive.google.com/uc?export=view&id=`

For example, the URL for the baseline U-Net model is `https://drive.google.com/uc?export=view&id=1cg2BDS2WqwIvicihDJFxak7FiffQMGdu`

See if you can download the file from that link.
