### ISSUE TITLE
Little information

### ISSUE THREAD

**Issue by playdasegunda** [serkansulun/deep-music-enhancer#4]
Hello how are you? I ended up finding this tool, and I found it interesting,

But the inference information is very poor,

Would it be possible to help us in this step of processing our own sounds?

Thank you!

Yours sincerely,
Lucas Rodrigues.

**Comment by serkansulun** [comment]
You should first download a pretrained model, for example `unetda`. Check `config.py`, you should provide your data folder in `TEST_DIRS`. And then run the script `run.py` using the `--test` flag.

But honestly, this repository only demonstrates our paper, which makes the claim that these models are very prone to filter overfitting. So unless you know exactly which type of filter has band-limited the data, the models won't be useful. And in real-world scenarios, one can never know this exactly.
